"""Shared pieces for the blog system: paths, settings, posts, Markdown rendering and quality checks.

Everything here reads from and writes to the /blog folder only. The portfolio never imports or loads any of it.
"""
from __future__ import annotations

import datetime as dt
import html
import re
from dataclasses import dataclass, field
from pathlib import Path

import markdown
import yaml

SYSTEM_DIR = Path(__file__).resolve().parent          # blog/_system
BLOG_DIR = SYSTEM_DIR.parent                           # blog
POSTS_DIR = BLOG_DIR / "_src" / "posts"                # Markdown sources (underscore: GitHub Pages does not publish it)
TEMPLATES_DIR = SYSTEM_DIR / "templates"
GENERATED_MARK = "Generated by blog/_system/build.py"  # only folders whose page carries this mark are ever deleted
RESERVED_SLUGS = {"assets", "_src", "_system", "posts", "index", "feed", "sitemap", "tag", "category", "page"}

# Approved client names (portfolio rule): articles never name clients, so any of these in a post is an error
CLIENT_NAMES = ["Relife", "Prolex", "Elixr", "SMGrowthX", "ARBO", "FIREOX", "Infinix Holding", "Meem Solutions", "Digital Software Market"]


def inside_blog(path: Path) -> Path:
    """Guard: refuse to touch anything outside /blog."""
    path = path.resolve()
    if BLOG_DIR != path and BLOG_DIR not in path.parents:
        raise RuntimeError(f"Refusing to write outside the blog folder: {path}")
    return path


def load_config() -> dict:
    return yaml.safe_load((SYSTEM_DIR / "config.yml").read_text(encoding="utf-8"))


def today(cfg: dict) -> dt.date:
    sign, hh, mm = cfg["site"]["timezone_offset"][0], *cfg["site"]["timezone_offset"][1:].split(":")
    offset = dt.timedelta(hours=int(hh), minutes=int(mm)) * (1 if sign == "+" else -1)
    return dt.datetime.now(dt.timezone(offset)).date()


# ---------------------------------------------------------------------------------------------- posts

@dataclass
class Post:
    path: Path
    meta: dict
    body_md: str
    html: str = ""
    toc: list = field(default_factory=list)       # [(id, label)]
    first_paragraph: str = ""
    words: int = 0

    @property
    def slug(self) -> str:
        return str(self.meta.get("slug", ""))

    @property
    def date(self) -> dt.date:
        return as_date(self.meta.get("date"))

    @property
    def updated(self) -> dt.date:
        return as_date(self.meta.get("updated") or self.meta.get("date"))

    @property
    def draft(self) -> bool:
        return bool(self.meta.get("draft", False))


def as_date(value) -> dt.date:
    if isinstance(value, dt.datetime):
        return value.date()
    if isinstance(value, dt.date):
        return value
    return dt.date.fromisoformat(str(value))


def split_front_matter(text: str) -> tuple[dict, str]:
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n?(.*)$", text.replace("\r\n", "\n"), re.S)
    if not m:
        raise ValueError("missing front matter (the file must start with a --- block)")
    return yaml.safe_load(m.group(1)) or {}, m.group(2)


def load_posts() -> list[Post]:
    posts = []
    for path in sorted(POSTS_DIR.glob("*.md")):
        meta, body = split_front_matter(path.read_text(encoding="utf-8"))
        posts.append(Post(path, meta, body))
    return posts


def front_matter_text(meta: dict) -> str:
    """Write front matter in the same readable layout as the hand-written posts."""
    def q(v):
        return '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'

    def lst(v):
        return "[" + ", ".join(q(x) for x in v) + "]"

    lines = ["---"]
    for key in ["title", "seo_title", "short_title", "description", "dek", "slug", "date", "updated", "author",
                "category", "tags", "keywords", "draft", "generated_by"]:
        if key not in meta:
            continue
        v = meta[key]
        if isinstance(v, list):
            lines.append(f"{key}: {lst(v)}")
        elif isinstance(v, bool):
            lines.append(f"{key}: {'true' if v else 'false'}")
        elif isinstance(v, (dt.date, int)):
            lines.append(f"{key}: {v}")
        else:
            lines.append(f"{key}: {q(v)}")
    lines.append("---")
    return "\n".join(lines) + "\n\n"


# ---------------------------------------------------------------------------------------------- rendering

def slugify(text: str, sep: str = "-") -> str:
    text = re.sub(r"[^\w\s-]", "", html.unescape(text).lower().replace("&", " and "))
    return re.sub(r"[\s_-]+", sep, text).strip(sep)


def plain_text(fragment: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", fragment))).strip()


def count_words(text: str) -> int:
    return len(re.findall(r"[A-Za-z0-9][\w'’\-]*", text))


def _md() -> markdown.Markdown:
    return markdown.Markdown(
        extensions=["extra", "toc", "sane_lists"],
        extension_configs={"toc": {"toc_depth": "2-2", "slugify": slugify}},
    )


def render_markdown(body: str, base_url: str) -> tuple[str, list, str, int]:
    """Markdown → HTML in the site's prose style. Returns (html, toc, first_paragraph_text, word_count).

    Extras on top of standard Markdown:
      ## Heading {#custom-id data-toc-label="Short TOC label"}
      :::callout Label            (blue-labelled box, closed by a line with :::)
      Table: Caption text         (line directly above a table)
    """
    body = body.replace("\r\n", "\n")

    # Callout boxes → placeholders, rendered separately so Markdown inside them still works
    callouts = []

    def take_callout(m):
        kind, label = m.group(1).lower(), (m.group(2) or "").strip()
        label = label or {"callout": "Note", "takeaway": "Key takeaway", "warning": "Watch out"}.get(kind, kind.capitalize())
        inner = _md().convert(m.group(3).strip())
        callouts.append(
            f'<aside class="callout" aria-label="{html.escape(label)}">\n'
            f'<p class="callout__label">{html.escape(label)}</p>\n{inner}\n</aside>'
        )
        return f"\n\nBLOGCALLOUT{len(callouts) - 1}\n\n"

    # :::callout Label / :::tip / :::note / :::warning / :::takeaway (AI models use all of these)
    body = re.sub(r"^:::[ \t]*(callout|tip|note|warning|takeaway|info)\b[ \t]*(.*?)\n(.*?)\n:::[ \t]*$",
                  take_callout, body, flags=re.M | re.S | re.I)

    # "Table: caption" lines → remembered per table, in order
    captions, lines, out, table_no = {}, body.split("\n"), [], 0
    for i, line in enumerate(lines):
        if re.match(r"^Table:\s+\S", line):
            captions[table_no + 1] = line.split(":", 1)[1].strip()   # applies to the next table
            continue
        if line.lstrip().startswith("|") and i + 1 < len(lines) and re.match(r"^\s*\|?\s*:?-{3,}", lines[i + 1]):
            table_no += 1
        out.append(line)
    body = "\n".join(out)

    md = _md()
    result = md.convert(body)
    toc = [(t["id"], html.unescape(t["name"])) for t in md.toc_tokens]

    for n, block in enumerate(callouts):
        result = result.replace(f"<p>BLOGCALLOUT{n}</p>", block)

    # Tables: scroll wrapper, caption, column/row header scopes
    counter = iter(range(1, 10_000))

    def fix_table(m):
        n = next(counter)
        t = m.group(0)
        t = re.sub(r"<th( style=\"[^\"]*\")?>", r'<th scope="col"\1>', t)
        head, sep, rest = t.partition("<tbody>")
        rest = re.sub(r"<tr>\s*<td( style=\"[^\"]*\")?>(.*?)</td>", r'<tr><th scope="row"\1>\2</th>', rest, flags=re.S)
        t = head + sep + rest
        if n in captions:
            t = t.replace("<table>", f"<table>\n<caption>{html.escape(captions[n])}</caption>", 1)
        return f'<div class="table-wrap">\n{t}\n</div>'

    result = re.sub(r"<table>.*?</table>", fix_table, result, flags=re.S)

    # Links to other websites open in a new tab
    def fix_link(m):
        href = m.group(1)
        if href.startswith(("http://", "https://")) and not href.startswith(base_url):
            return f'<a href="{href}" target="_blank" rel="noopener">'
        return m.group(0)

    result = re.sub(r'<a href="([^"]+)">', fix_link, result)

    first = re.search(r"<p>(.*?)</p>", result, re.S)
    return result, toc, plain_text(first.group(1)) if first else "", count_words(plain_text(result))


def render_post(post: Post, base_url: str) -> Post:
    post.html, post.toc, post.first_paragraph, post.words = render_markdown(post.body_md, base_url)
    return post


# ---------------------------------------------------------------------------------------------- checks

LINK_RE = re.compile(r'href="([^"]+)"')
BANNED = [
    (r"\b\d+(?:\.\d+)?\s?%", "uses a percentage statistic (no invented statistics; describe it in words instead)"),
    (r"\b(?:studies|research|surveys?|statistics|data|experts?)\s+(?:show|shows|showed|found|finds|suggests?|say|says|prove|proves)\b",
     "cites unnamed research or experts"),
    (r"\baccording to (?:a|one|recent|the latest|new) (?:study|survey|report|research)", "cites an unnamed study or survey"),
    (r"\bas an ai\b|\blanguage model\b", "mentions being an AI"),
    (r"in today'?s (?:digital|fast-paced|modern|competitive)|\bdelve\b|game[- ]changer|unlock the (?:power|potential)|look no further|\bin conclusion\b",
     "uses a cliché phrase"),
]
MONEY_RE = re.compile(r"(?:\$|USD|PKR|Rs\.?|€|£)\s?\d[\d,.]*|\d[\d,.]*\s?(?:dollars|rupees)", re.I)


def keyword_in(keyword: str, text: str) -> bool:
    norm = lambda s: re.sub(r"[^a-z0-9]+", " ", html.unescape(s).lower()).strip()
    return norm(keyword) in norm(text)


def check_post(post: Post, cfg: dict, *, strict: bool, known_slugs: set[str] = frozenset()) -> tuple[list, list]:
    """Return (errors, warnings). strict=True is used for AI-written posts and adds content-safety rules."""
    m, errors, warnings = post.meta, [], []
    site = cfg["site"]

    for key in ["title", "description", "dek", "slug", "date", "category", "tags", "keywords"]:
        if not m.get(key):
            errors.append(f"front matter is missing '{key}'")
    if errors:
        return errors, warnings

    page_title = f"{m.get('seo_title') or m['title']} | {site['name']}"
    if len(page_title) > 60:
        errors.append(f"page title is {len(page_title)} characters, max 60: \"{page_title}\" (shorten seo_title)")
    if len(m["description"]) > 160:
        errors.append(f"description is {len(m['description'])} characters, max 160")
    if strict and len(m["description"]) < 80:
        errors.append("description is too short (aim for 120–160 characters)")
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", post.slug) or post.slug in RESERVED_SLUGS:
        errors.append(f"slug '{post.slug}' must be lowercase words joined by hyphens and not a reserved name")
    if m["category"] not in cfg["writing"]["categories"]:
        errors.append(f"category '{m['category']}' is not one of {cfg['writing']['categories']}")
    if not isinstance(m["tags"], list) or not isinstance(m["keywords"], list):
        errors.append("tags and keywords must be lists like [a, b]")
        return errors, warnings
    try:
        post.date
    except ValueError:
        errors.append("date must look like 2026-10-04")

    if not post.html:
        render_post(post, site["base_url"])
    if re.search(r"(^|>)\s*:::", post.html, re.M):
        errors.append("a ':::' box was not closed or uses an unknown type; use ':::callout Label' … ':::'")
    if "<h1" in post.html:
        errors.append("the article body must not contain an h1 (# heading); the title is the only h1")
    if len(post.toc) < (4 if strict else 2):
        errors.append(f"needs at least {4 if strict else 2} '## ' section headings (found {len(post.toc)})")
    ids = [i for i, _ in post.toc]
    if len(ids) != len(set(ids)):
        errors.append("two sections have the same heading id")

    main = m["keywords"][0]
    places = {"title": m["title"], "description": m["description"], "first paragraph": post.first_paragraph}
    missing = [name for name, text in places.items() if not keyword_in(main, text)]
    if slugify(main) not in post.slug and not all(w in post.slug.split("-") for w in slugify(main).split("-")):
        missing.append("slug")
    if missing:
        (errors if strict else warnings).append(f"main keyword '{main}' is missing from: {', '.join(missing)}")

    if strict:
        lo, hi = cfg["writing"]["min_words"], cfg["writing"]["max_words"]
        if not lo * 0.9 <= post.words <= hi * 1.15:
            errors.append(f"article is {post.words} words; it must be between {lo} and {hi}")
        if "faq" not in ids:
            errors.append("must end with a '## Frequently asked questions {#faq data-toc-label=\"FAQ\"}' section")
        text = plain_text(post.html) + " " + " ".join(str(v) for v in m.values())
        for pattern, why in BANNED:
            hit = re.search(pattern, text, re.I)
            if hit:
                errors.append(f"{why}: \"{hit.group(0)}\"")
        for name in CLIENT_NAMES:
            if re.search(rf"\b{re.escape(name)}\b", text, re.I):
                errors.append(f"names a client or employer ('{name}'); articles must not name clients")
        for href in LINK_RE.findall(post.html):
            if not link_allowed(href, known_slugs):
                errors.append(f"link not allowed: {href} (only website home pages like https://www.shopify.com/, "
                              f"../../#work, ../../#about, ../../#contact, or ../<existing-post-slug>/)")
        for money in sorted(set(MONEY_RE.findall(plain_text(post.html)))):
            warnings.append(f"mentions a price ({money}); prices change, so double-check it")
    return errors, warnings


def link_allowed(href: str, known_slugs) -> bool:
    if href.startswith("#") or re.fullmatch(r"\.\./\.\./#(work|about|skills|clients|contact)", href):
        return True
    m = re.fullmatch(r"\.\./([a-z0-9-]+)/", href)
    if m:
        return m.group(1) in known_slugs
    # Only home pages of other websites: deep links invented by an AI are often broken
    return bool(re.fullmatch(r"https://[a-z0-9.-]+\.[a-z]{2,}/?", href))
